vich_uploader:
    db_driver: orm

    mappings:
        user_kbis:
            namer: vich_uploader.namer_origname
            uri_prefix: '%app.path.user_kbis%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_kbis%'


